memser-spaceport/labweek24-events

events/labweek-24/pg/Funding-the-Commons.json
New event added - Funding the Commons
=> New event added

events/labweek-24/pg/Funding-the-Commons.json
=> Ftc event desc updated

events/labweek-24/pg/Funding-the-Commons.json
=> Ftc event sponsors updated

events/labweek-24/pg/codeX-Future-law.json
=> Add event CodeX

events/labweek-24/pg/Earth-Commons.json, events/labweek-24/pg/Funding-the-Commons-Speaker-Sponsor-Dinner.json, events/labweek-24/pg/Institutional-Ecologies.json, events/labweek-24/pg/PL-10-Year-Anniversary.json, events/labweek-24/pg/PL-x-OrangeDAO.json, events/labweek-24/pg/Science-advancement-opportunities.json, events/labweek-24/pg/deSci-meetup.json, events/labweek-24/pg/wiki-AI-day.json
=> Adding new events

events/labweek-24/pg/Funding-the-Commons-Speaker-Sponsor-Dinner.json
=> Tag update

events/labweek-24/pg/PL-10-Year-Anniversary.json
Location removed from PL 10 year anniversary event
=> Location removed from PL 10 year anniv event

events/labweek-24/pg/Berkeley-RDI-Accelerator-Program-Demo-Day.json, events/labweek-24/pg/Funding-the-Commons-Party.json, events/labweek-24/pg/Funding-the-Commons.json, events/labweek-24/pg/PL-10-Year-Anniversary.json, events/labweek-24/pg/wiki-AI-day.json
Newly added events - 
- Berkeley RDI Accelerator Program Demo Day
- Funding the Commons Party
Updated events - 
- Funding the Commons Speaker and Sponsor Dinner
- Funding the Commons
- PL 10 Year Anniversary
- Wiki AI Day
=> Events update

events/labweek-24/pg/Funding-the-Commons-Party.json
Funding the Commons party event end time update
=> Event's time update

events/labweek-24/pg/Argentina-Opportunity-Igniting-Innovtion.json, events/labweek-24/pg/Berkeley-RDI-Accelerator-Program-Demo-Day.json, events/labweek-24/pg/PL-10-Year-Anniversary.json, events/labweek-24/pg/wiki-AI-day.json
Event logo updated for Berkeley RDI event
=> Event logo and Location updated for Berkeley RDI and PL 10th year anniversary events respectively

events/labweek-24/pg/Berkeley-RDI-Accelerator-Program-Demo-Day.json, events/labweek-24/pg/wiki-AI-day.json
=> Event names reverted

events/labweek-24/pg/Paths-Pgrs-Crypto-AI.json, events/labweek-24/pg/Paths-Pgrs-Long-Biotech.json, events/labweek-24/pg/Paths-Pgrs-Molclr-Nano-Tech.json, events/labweek-24/pg/Paths-Pgrs-Neuro-Tech.json, events/labweek-24/pg/Paths-Pgrs-Space.json
=> Adding Path series events

events/labweek-24/pg/Paths-Pgrs-Crypto-AI.json, events/labweek-24/pg/Paths-Pgrs-Long-Biotech.json, events/labweek-24/pg/Paths-Pgrs-Molclr-Nano-Tech.json, events/labweek-24/pg/Paths-Pgrs-Neuro-Tech.json, events/labweek-24/pg/Paths-Pgrs-Space.json
Path series events' location url added
=> Path series events' location url added

events/labweek-24/pg/Fil-pgf.json
=> Fil pgf event added

events/labweek-24/pg/Wiki-x-AI-Hackathon.json
Wiki AI day event timing updated
=> Wiki AI day event timing updated

events/labweek-24/pg/Public-Goods-Funding-Dinner.json
=> PGF dinner new event addded

events/labweek-24/pg/deSci-tax-day-social.json
@WinsCodes-  Edit to event.
cc:  @pandeyanujk
=> Update and rename deSci-meetup.json to deSci-tax-day-social.json

events/labweek-24/pg/Fil-pgf.json, events/labweek-24/pg/Funding-the-Commons-Party.json, events/labweek-24/pg/Funding-the-Commons-Speaker-Sponsor-Dinner.json, events/labweek-24/pg/Funding-the-Commons.json, events/labweek-24/pg/Hyerpcerts-working-sessions.json, events/labweek-24/pg/PL-x-OrangeDAO.json
Events updated and new hypercerts event added
=> Events updated and new hypercerts event added

events/labweek-24/pg/Public-Goods-Funding-Dinner.json
Website link and location url updated
=> Website link and location url updated

events/labweek-24/pg/Earth-Commons.json, events/labweek-24/pg/Funding-the-Commons.json, events/labweek-24/pg/codeX-Future-law.json
=> Updated events

events/labweek-24/pg/Stanford-blockchain-governance-summit.json
Added new event Stanford blockchain
=> Added new event Stanford blockchain

events/labweek-24/pg/pl-meetup.json
=> Updated event pl meetup
